
services:
  # MongoDB Database

  # API Application
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dentist-api
    restart: unless-stopped
    environment:
      NODE_ENV: production
      PORT: 4001
      MONGODB_URI: mongodb+srv://teamdigiavocado:3HSGYBSjvgZ52qRm@test-1.6cem02a.mongodb.net/?retryWrites=true&w=majority
      JWT_SECRET_KEY: DENTIST
      JWT_EXPIRE: 1d
    ports:
      - "4001:4001"
    volumes:
      - api_logs:/app/logs
    networks:
      - dentist-network
   

volumes:
  mongodb_data:
    driver: local
  api_logs:
    driver: local

networks:
  dentist-network:
    driver: bridge